#!/usr/bin/env lua

if _VERSION < 'Lua 5.4' then
  io.stderr:write('A desktop platform running Lua 5.4 or later is required.\n')
  os.exit(1)
end

_G.assert = require('mrsh.overrides.assert')
_G.printf = require('mrsh.overrides.printf')
_G.fprintf = require('mrsh.overrides.fprintf')

_G.Object = require('mrsh.core.object')

_G.ROOT = Object()

ROOT:on('startup', function(self)
  printf('Hello, %s!\n', os.getenv('USER') or 'dummy')
end)

ROOT:emit('startup')
